apiVersion: v1
kind: ConfigMap
metadata:
  name: php-env-config-accesscontrol
  labels:
    tier: backend
data:
  env.json : | 
    {
    "environment":"inter1",
    "db":{
      "postgresql":{
          "host":"103.56.157.180",
          "dbname":"inter_accesscontrol_symper_vn",
          "username":"postgres",
          "password":"SymPER!!12345_1"
      }
    }}
