apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-{APP_NAME}
  labels:
    tier: backend
data:
  env.json: |
    {
      "environment":"{ENVIRONMENT}",
      "db":{
        "postgresql":{
            "host":"{POSTGRES_HOST}",
            "dbname":"{POSTGRES_DB}",
            "username":"{POSTGRES_USER}",
            "password":"{POSTGRES_PASS}"
        },
        "cache": {
            "host": "{CACHE_HOST}",
            "password": "{CACHE_PASSWORD}"
        }
      },
      "kafka":"k1.symper.vn"
    }
