apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-{APP_NAME}
  labels:
    tier: backend
data:
  env.json: |
    {
      "environment":"{ENVIRONMENT}",
      "db":{
        "postgresql":{
            "host":"{POSTGRES_HOST}",
            "dbname":"{POSTGRES_DB}",
            "username":"{POSTGRES_USER}",
            "password":"{POSTGRES_PASS}"
        },
        "cache": {
            "host": "{CACHE_HOST}",
            "password": "{CACHE_PASS}"
        }
      },
      "kafka":"{KAFKA_PREFIX}",
      "domains": {
        "ACCESS_CONTROL_SERVICE": "http://accesscontrol.{SERVICE_ENV}.svc.cluster.local",
        "ACCOUNT_SERVICE": "http://account.{SERVICE_ENV}.svc.cluster.local",
        "APP_MANAGEMENT_SERVICE": "http://apps-management.{SERVICE_ENV}.svc.cluster.local",
        "BI_SERVICE": "http://bi-service.{SERVICE_ENV}.svc.cluster.local",
        "COMMENT_SERVICE": "http://comment-service.{SERVICE_ENV}.svc.cluster.local",
        "DATA_IO_SERVICE": "http://data-io.{SERVICE_ENV}.svc.cluster.local",
        "FILE_SERVICE": "http://file-service.{SERVICE_ENV}.svc.cluster.local",
        "IO_SERVICE": "http://io-service.{SERVICE_ENV}.svc.cluster.local",
        "KANBAN_SERVICE": "http://kanban-service.{SERVICE_ENV}.svc.cluster.local",
        "NOTIFI_SERVICE": "http://notifi.{SERVICE_ENV}.svc.cluster.local",
        "ORGCHART_SERVICE": "http://orgchart.{SERVICE_ENV}.svc.cluster.local",
        "SDOCUMENT_MANAGEMENT_SERVICE": "http://sdocument-management.{SERVICE_ENV}.svc.cluster.local",
        "SDOCUMENT_SERVICE": "http://sdocument.{SERVICE_ENV}.svc.cluster.local",
        "SYQL_SERVICE": "http://syql.{SERVICE_ENV}.svc.cluster.local",
        "UI_SERVICE": "http://ui.{SERVICE_ENV}.svc.cluster.local",
        "WORKFLOW_EXTEND_SERVICE": "http://workflow-extend.{SERVICE_ENV}.svc.cluster.local",
        "WORKFLOW_MODELER_SERVICE": "http://workflow-modeler.{SERVICE_ENV}.svc.cluster.local",
        "DATA_CONNECTOR_SERVICE": "http://data-connector.{SERVICE_ENV}.svc.cluster.local",
        "OBJECT_RELATION": "http://object-relation.{SERVICE_ENV}.svc.cluster.local",
        "LOG_SERVICE": "http://log.{SERVICE_ENV}.svc.cluster.local",
        "SEARCH_SERVICE": "http://search.{SERVICE_ENV}.svc.cluster.local",
        "WORKFLOW_SERVICE": "http://tomcat-workflow.{SERVICE_ENV}.svc.cluster.local",
        "LUFFY_SERVICE": "https://luffy.symper.vn"
      }
    }

  replace_vars.sh: |
    #!/bin/bash
    source /vault/secrets/config-postgres:
    source /vault/secrets/config-cache:
    cp -f /src/env.json /var/www/app/env.json

    sed -i -e "s/{POSTGRES_USER}/$POSTGRES_USER/g" \
           -e "s/{POSTGRES_PASS}/$POSTGRES_PASS/g" \
           -e "s/{CACHE_PASS}/$CACHE_PASS/g" /var/www/app/env.json