apiVersion: v1
kind: ConfigMap
metadata:
  name: php-env-config-accesscontrol
  labels:
    tier: backend
data:
  env.json : | 
    {
    "environment":"{ENVIRONMENT}",
    "db":{
      "postgresql":{
          "host":"{DB_HOST}",
          "dbname":"{ENVIRONMENT_}accesscontrol_symper_vn",
          "username":"{POSTGRES_USER}",
          "password":"{POSTGRES_PASSWORD}"
      }
    }}
