apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: accesscontrol-nginx-memory-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: nginx-accesscontrol
  minReplicas: 1
  maxReplicas: 10
  # Thực hiện scale CPU hoạt động ở 50% so với CPU mà POD yêu cầu
  targetMemoryUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: accesscontrol-nginx-cpu-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: nginx-accesscontrol
  minReplicas: 1
  maxReplicas: 10
  # Thực hiện scale CPU hoạt động ở 50% so với CPU mà POD yêu cầu
  targetCPUUtilizationPercentage: 70

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: accesscontrol-php-memory-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: php-accesscontrol
  minReplicas: 1
  maxReplicas: 10
  # Thực hiện scale CPU hoạt động ở 50% so với CPU mà POD yêu cầu
  targetMemoryUtilizationPercentage: 70

---


apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: accesscontrol-php-cpu-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: php-accesscontrol
  minReplicas: 1
  maxReplicas: 10
  # Thực hiện scale CPU hoạt động ở 50% so với CPU mà POD yêu cầu
  targetCPUUtilizationPercentage: 70