apiVersion: v1
kind: Service
metadata:
  name: php-accesscontrol
  labels:
    tier: backend
spec:
  selector:
    app: php-accesscontrol
    tier: backend
  ports:
    - name: php-accesscontrol
      port: 9000

